# Generated by Django 5.0.4 on 2024-04-07 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='', max_length=150)),
                ('cidade', models.CharField(default='', max_length=150)),
                ('logradouro', models.CharField(default=0, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('cnpj', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vend', models.IntegerField(primary_key=True, serialize=False)),
                ('vendas', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('cnpj_l', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=150)),
                ('fk_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_rest.vendedor')),
            ],
        ),
    ]
